spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_employee_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: a0bTfb5p$t3d12h3
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  flyway:
    baseline-on-migrate: true